version: '3'

services:
    gql-master:
        container_name: gql-master
        image: gdsoumya/gql-node-master

    go-agent:
        container_name: go-agent
        image: gdsoumya/go-agent
        depends_on:
            - gql-master
