apiVersion: v1
kind: Service
metadata:
    name: gql-svc
spec:
    selector:
        app: gql
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 30036
        #   nodePort: 32000
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gql
    labels:
        app: gql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gql
    template:
        metadata:
            labels:
                app: gql
        spec:
            containers:
                - name: gql-server
                  image: 'gdsoumya/gql-go-server'
                  ports:
                      - containerPort: 8080
                  imagePullPolicy: Always
