apiVersion: apps/v1
kind: Deployment
metadata:
    name: subscriber
    labels:
        app: subscriber
spec:
    replicas: 2
    selector:
        matchLabels:
            app: subscriber
    template:
        metadata:
            labels:
                app: subscriber
        spec:
            containers:
                - name: gql-node-master
                  image: 'gdsoumya/gql-node-master'
                  env:
                      - name: GQL_SERVER
                        value: '18.217.59.146:30036/query'
                - name: go-agent
                  image: 'gdsoumya/go-agent'
